services:
  redis:
    image: redis:7.0-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/urlshortener.db
      - APP_BASE_URL=http://localhost:8080
    volumes:
      - ./data:/data
    networks:
      - url-shortener-network
    restart: unless-stopped

networks:
  url-shortener-network:
    driver: bridge

volumes:
  redis_data:
